name: Test

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.4']
        extensions: ['mongodb-2.3, zip']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}

      - name: Check Environment
        run: |
          php --ri mongodb
